name: go_feature_flag
description: >-
  An OpenFeature provider for GO Feature Flag, supporting the REMOTE
  evaluation mode against a go-feature-flag relay-proxy.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.13.1

dependencies:
  http: ^1.2.0
  logging: ^1.2.0
  openfeature_dart_server_sdk: ^0.0.26

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
